spring:
  lifecycle:
    #优雅停机等待的最大时间
    timeout-per-shutdown-phase: 60s
  application:
    #spring服务名称
    name: TRD  #交易trade
  datasource:
    #oracle数据库密码
    password: ${APP_DB_PASSWORD:huangyiran}
    #type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 最小连接池数量
      min-idle: ${APP_DB_MIN_IDLE:5}
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 最大连接池数量
      max-active: ${APP_DB_MAX_ACTIVE:10}
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #申请连接的时候检测，如果空闲时间大于imeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #用来检测连接是否有效的sql，要求是一个查询语句,如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validation-query: SELECT 'X' FROM DUAL
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 最小空闲连接数保活
      keep-alive: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # 初始化物理连接个数
      initial-size: ${APP_DB_INITIAL_SIZE:5}
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
    #oracle数据库驱动
    driver-class-name: ${ APP_DB_DRIVER:oracle.jdbc.OracleDriver}
    # oracle数据库连接
    url: ${APP_DB_URL:jdbc:oracle:thin:@127.0.0.1/test}
    # oracle用户名
    username: ${APP_DB_USER:huangyiran}
mybatis:
  # mybatis的sqlmapper对应xml的路径
  mapper-locations: classpath:sqlmap/**/*.xml

server:
  #应用对外服务端口
  port: 8080
  servlet:
    #应用上下文根路径
    context-path: /
  #开启优雅停机，默认IMMEDIATE是立即关机
  shutdown: graceful

logging:
  level:
    com.example.purchase: WARN